[package]
name = "symgen"
description = "Symbol exports and link manifest generator for game modding"
authors = ["Luke Street <luke@street.dev>"]
license = "MIT OR Apache-2.0"
version = "1.1.0"
edition = "2024"
publish = false
repository = "https://github.com/encounter/symgen"
readme = "README.md"
categories = ["command-line-utilities"]
rust-version = "1.85"

[profile.release]
panic = "abort"

[profile.release-lto]
inherits = "release"
lto = "fat"
strip = "debuginfo"
codegen-units = 1

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
argp = "0.4"
cpp_demangle = "0.5"
enable-ansi-support = "0.3"
log = "0.4"
object = { version = "0.39", default-features = false, features = ["read", "archive", "coff", "elf", "macho", "std"] }
pdb = "0.8"
supports-color = "3.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zerocopy = { version = "0.8", features = ["derive"] }
zstd = "0.13"

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = "0.1"
